### ISSUE TITLE
Dependencies error

### ISSUE THREAD

**Issue by rdricco** [MertcanGokgoz/Jekyll-Spotify#1]
I got this when tried to run using bundle exec:

`         Requiring: jekyll-spotify
  Dependency Error: Yikes! It looks like you don't have jekyll-spotify or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- jekyll-spotify' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/!
jekyll 3.3.1 | Error:  jekyll-spotify`

I installed the gem and have on gemfile and config.yml. 

I will install via plugins folder for now.

**Comment by MertcanGokgoz** [comment]
Thank you for your feedback,

I will check and return as soon as possible

thank you for your interest :+1:
